#define PIN_MATRIX_BIG_COLOR 0
#define SHIFT_MATRIX_BIG_COLOR 2
#define PIN_MATRIX_BIG_GND 4
#define SHIFT_MATRIX_BIG_GND 12
#define LATCH_MATRIX_BIG 16
#define PIN_MATRIX_SMALL 17
#define SHIFT_MATRIX_SMALL 18
#define LATCH_MATRIX_SMALL 19
#define PIN_SIEBENSEG 21
#define SHIFT_SIEBENSEG 22
#define LATCH_SIEBENSEG 23
#define NOT_ENABLE 27
//#define NOT_RESET_ALL 35 //pulled to 3,3V
#define PIN_MUSIC_L 25
#define PIN_MUSIC_R 26
#define TOUCH_UP 13
#define TOUCH_LEFT 14
#define TOUCH_DOWN 15
#define TOUCH_RIGHT 32
#define TOUCH_START 33
#define TOUCH_RESET 34

#define STANDARD_DELAY_TIME_MS 1000
